[0m21:23:39.607770 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021894869D00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218972FDD30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218972FDAF0>]}


============================== 21:23:39.610761 | f1784519-b484-4f97-90c0-0b74b4b03f36 ==============================
[0m21:23:39.610761 [info ] [MainThread]: Running with dbt=1.8.1
[0m21:23:39.610761 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Fikri Tech\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:23:44.569191 [debug] [MainThread]: Starter project path: D:\Data Engineering Series\dbt_snowflake\.venv\lib\site-packages\dbt\include\starter_project
[0m21:23:44.576171 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:23:44.577168 [info ] [MainThread]: Setting up your profile.
[0m21:24:39.971449 [info ] [MainThread]: Profile data_pipeline written to C:\Users\Fikri Tech\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:24:39.973445 [debug] [MainThread]: Command `dbt init` succeeded at 21:24:39.973445 after 60.43 seconds
[0m21:24:39.974442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021894869D00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000218972FDA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002189734F3D0>]}
[0m21:24:39.975439 [debug] [MainThread]: Flushing usage events
[0m21:28:48.481291 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021486039CA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021488ACBC70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021488ACBB50>]}


============================== 21:28:48.484285 | 11e14c79-2898-4d67-9ce0-2fd699ecc9b5 ==============================
[0m21:28:48.484285 [info ] [MainThread]: Running with dbt=1.8.1
[0m21:28:48.484817 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Fikri Tech\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt deps', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:28:48.484817 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Data Engineering Series\dbt_snowflake\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:28:48.486820 [debug] [MainThread]: Command `dbt deps` failed at 21:28:48.486820 after 0.07 seconds
[0m21:28:48.486820 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021486039CA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021488ACBCD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021488ACBC10>]}
[0m21:28:48.486820 [debug] [MainThread]: Flushing usage events
[0m21:35:16.791279 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD98679CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD9B107280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD9B107490>]}


============================== 21:35:16.794275 | 51937eb4-ef0a-47b8-bdb1-c60087341f91 ==============================
[0m21:35:16.794275 [info ] [MainThread]: Running with dbt=1.8.1
[0m21:35:16.795272 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Fikri Tech\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:35:16.795272 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Data Engineering Series\dbt_snowflake\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:35:16.797268 [debug] [MainThread]: Command `dbt deps` failed at 21:35:16.797268 after 0.07 seconds
[0m21:35:16.797268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD98679CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD9B107310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CD9B1073D0>]}
[0m21:35:16.798265 [debug] [MainThread]: Flushing usage events
